name: dart_only_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  hooks: ^1.0.1
  native_toolchain_rust: ^1.0.3

dev_dependencies:
  ffigen: ^20.1.0
  test: ^1.26.2
